config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :order_details
  resources :orders
  resources :customers
  resources :carts
  resources :categories
  resources :banners
  resources :products
  get 'home/index'
  get 'home/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html  
  get "/users/sign_out", to: "users#sign_out"
  # Defines the root path route ("/")
  root "home#index"
  get "/productos/buscador", to: "products#buscador", as: "buscar_producto"
  get "/productos/:id/agregar_carrito", to: "products#agregar_carrito", as: "agregar_carrito"
  get "/carrito/:id/vaciar_carrito", to: "carts#vaciar_carrito", as: "vaciar_carrito"
  get "/productos/:id/disminuye_cantidad", to: "products#disminuye_cantidad", as: "disminuye_cantidad"
  get "/productos/:id/aumenta_cantidad", to: "products#aumenta_cantidad", as: "aumenta_cantidad"
  get "/customer/:id/valida_cliente", to: "customers#valida_cliente", as: "valida_cliente"
  get "/order/:id/pedido", to: "orders#genera_pedido", as: "genera_orden"
  get "/order/:id/confirma", to: "orders#confirma_pedido", as: "confirma_pedido"

  namespace :paypal do
    resources :checkouts, only: [:create] do
      collection do
        get :complete
      end
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to genera_orden_path, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to genera_orden_path, notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def valida_cliente
    @customer = Customer.find_by(user_id: params[:id])
    if !@customer
      @customer = Customer.new
    end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:codigo, :nombre, :paterno, :materno, :rut, :nombre_completo, :direccion, :ciudad, :region, :pais, :telefono, :correo, :user_id)
    end
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">

  <p>
    <strong>Nombre:</strong>
    <%= customer.nombre %>
  </p>

  <p>
    <strong>Paterno:</strong>
    <%= customer.paterno %>
  </p>

  <p>
    <strong>Materno:</strong>
    <%= customer.materno %>
  </p>

  <p>
    <strong>Rut:</strong>
    <%= customer.rut %>
  </p>

  <p>
    <strong>Nombre completo:</strong>
    <%= customer.nombre_completo %>
  </p>

  <p>
    <strong>Direccion:</strong>
    <%= customer.direccion %>
  </p>

  <p>
    <strong>Ciudad:</strong>
    <%= customer.ciudad %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= customer.region %>
  </p>

  <p>
    <strong>Pais:</strong>
    <%= customer.pais %>
  </p>

  <p>
    <strong>Telefono:</strong>
    <%= customer.telefono %>
  </p>

  <p>
    <strong>Correo:</strong>
    <%= customer.correo %>
  </p>

  <p>
    <strong>User:</strong>
    <%= customer.user_id %>
  </p>

</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :rut, style: "display: block" %>
    <%= form.text_field :rut %>
  </div>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :paterno, style: "display: block" %>
    <%= form.text_field :paterno %>
  </div>

  <div>
    <%= form.label :materno, style: "display: block" %>
    <%= form.text_field :materno %>
  </div>

  <div>
    <%#= form.label :nombre_completo, style: "display: block" %>
    <%#= form.text_field :nombre_completo %>
  </div>

  <div>
    <%= form.label :direccion, style: "display: block" %>
    <%= form.text_field :direccion %>
  </div>

  <div>
    <%= form.label :ciudad, style: "display: block" %>
    <%= form.text_field :ciudad %>
  </div>

  <div>
    <%= form.label :region, style: "display: block" %>
    <%= form.text_field :region %>
  </div>

  <div>
    <%= form.label :pais, style: "display: block" %>
    <%= form.text_field :pais %>
  </div>

  <div>
    <%= form.label :telefono, style: "display: block" %>
    <%= form.text_field :telefono %>
  </div>

  <div>
    <%= form.label :correo, style: "display: block" %>
    <%= form.text_field :correo %>
  </div>

  <div>
    <%#= form.label :user_id, style: "display: block" %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>
  <br>
  <div>
    <%= form.submit "Siguiente", class: "btn btn-success" %>
    | <%= link_to "Regresar", carts_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Show this customer", @customer %> |
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Customers</h1>

<div id="customers">
  <% @customers.each do |customer| %>
    <%= render customer %>
    <p>
      <%= link_to "Show this customer", customer %>
    </p>
  <% end %>
</div>

<%= link_to "New customer", new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @customer %>

<div>
  <%= link_to "Edit this customer", edit_customer_path(@customer) %> |
  <%= link_to "Back to customers", customers_path %>

  <%= button_to "Destroy this customer", @customer, method: :delete %>
</div>

app/views/customers/valida_cliente.html.erb
<br><br>
<div class="container">

  <div class="card">
    <div class="card-header">
      <h1>Validando datos de cliente</h1>
    </div>
    <div class="card-body">
      <%= render "form", customer: @customer %>
    </div>
  </div>
</div> 