config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :order_details
  resources :orders
  resources :customers
  resources :carts
  resources :categories
  resources :banners
  resources :products
  get 'home/index'
  get 'home/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html  
  get "/users/sign_out", to: "users#sign_out"
  # Defines the root path route ("/")
  root "home#index"
  get "/productos/buscador", to: "products#buscador", as: "buscar_producto"
  get "/productos/:id/agregar_carrito", to: "products#agregar_carrito", as: "agregar_carrito"
  get "/carrito/:id/vaciar_carrito", to: "carts#vaciar_carrito", as: "vaciar_carrito"
  get "/productos/:id/disminuye_cantidad", to: "products#disminuye_cantidad", as: "disminuye_cantidad"
  get "/productos/:id/aumenta_cantidad", to: "products#aumenta_cantidad", as: "aumenta_cantidad"
  get "/customer/:id/valida_cliente", to: "customers#valida_cliente", as: "valida_cliente"
  get "/order/:id/pedido", to: "orders#genera_pedido", as: "genera_orden"
  get "/order/:id/confirma", to: "orders#confirma_pedido", as: "confirma_pedido"

  namespace :paypal do
    resources :checkouts, only: [:create] do
      collection do
        get :complete
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def genera_pedido
    @carrito = Cart.where(user_id: current_user.id, pedido: 0)
  end

  def confirma_pedido
    @carrito = Cart.where(user_id: params[:id], pedido: 0)
    cliente = Customer.find_by(user_id: params[:id])

    if cliente 
      folio = Order.count(:id) + 1
      total = @carrito.sum("cantidad * precio")
      orden = Order.new
      orden.fecha = Time.now
      orden.folio = folio
      orden.customer_id = cliente.id
      orden.estatus = 1
      orden.total = total
      orden.save

      @carrito.each do |cart|
        detalle = OrderDetail.new
        detalle.order_id = orden.id
        detalle.product_id = cart.product_id
        detalle.cantidad = cart.cantidad
        detalle.precio = cart.precio
        detalle.save
      end

      @carrito.update(pedido: 1)      

      @orden_id = orden.id
    else
     
    end  

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:fecha, :folio, :customer_id, :estatus, :total)
    end
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :fecha, style: "display: block" %>
    <%= form.date_field :fecha %>
  </div>

  <div>
    <%= form.label :folio, style: "display: block" %>
    <%= form.number_field :folio %>
  </div>

  <div>
    <%= form.label :customer_id, style: "display: block" %>
    <%= form.text_field :customer_id %>
  </div>

  <div>
    <%= form.label :estatus, style: "display: block" %>
    <%= form.number_field :estatus %>
  </div>

  <div>
    <%= form.label :total, style: "display: block" %>
    <%= form.text_field :total %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Fecha:</strong>
    <%= order.fecha %>
  </p>

  <p>
    <strong>Folio:</strong>
    <%= order.folio %>
  </p>

  <p>
    <strong>Customer:</strong>
    <%= order.customer_id %>
  </p>

  <p>
    <strong>Estatus:</strong>
    <%= order.estatus %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= order.total %>
  </p>

</div>

app/views/orders/confirma_pedido.html.erb
+<br><br>
<div class="container">

  <div class="card">
    <div class="card-header">
      <h1>Pagar pedido</h1>
    </div>
    <div class="card-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>&nbsp;</th>
            <th>Codigo</th>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th>Precio</th>
            <th>Importe</th>
          </tr>
        </thead>
        <tbody>
          <% total = 0 %>
          <% @carrito.each do |cart| %>
            <% importe = cart.cantidad * cart.precio %>
            <% total += importe %> 
            <tr>
              <td width="20%"><%= image_tag(cart.product.image, style: "max-width: 20%") if cart.product.image.attached? %></td>
              <td width="10%"><%= cart.product.codigo %></td>
              <td width="40%"><%= cart.product.nombre %></td>
              <td width="10%" class="text-center"><%= cart.cantidad %></td>
              <td width="10%" class="text-center"><%= cart.precio %></td>
              <td width="10%" class="text-end"><%= importe %></td>  
            </tr>
          <% end %>
          <tr>
            <td colspan="5" class="text-end fw-bold fs-5">TOTAL A PAGAR</td>
            <td class="text-end fw-bold fs-5"><%= total %></td>
          </tr>
        <tbody>  
      </table>  
      <br>
      <%= form_with url: "/paypal/checkouts", method: :post, authenticity_token: true do |form| %>
        <%= form.hidden_field "orden_id", value: @orden_id %>
        <%= form.submit "Pagar", class: "btn btn-primary" %>
        | <%= link_to "Cancelar", vaciar_carrito_path(current_user.id), class: "btn btn-danger" %>  
      <% end %>

       
      
    </div>
  </div>  
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/genera_pedido.html.erb
<br><br>
<div class="container">

  <div class="card">
    <div class="card-header">
      <h1>Confirmación de pedido</h1>
    </div>
    <div class="card-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>&nbsp;</th>
            <th>Codigo</th>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th>Precio</th>
            <th>Importe</th>
          </tr>
        </thead>
        <tbody>
          <% total = 0 %>
          <% @carrito.each do |cart| %>
            <% importe = cart.cantidad * cart.precio %>
            <% total += importe %> 
            <tr>
              <td width="20%"><%= image_tag(cart.product.image, style: "max-width: 20%") if cart.product.image.attached? %></td>
              <td width="10%"><%= cart.product.codigo %></td>
              <td width="40%"><%= cart.product.nombre %></td>
              <td width="10%" class="text-center"><%= cart.cantidad %></td>
              <td width="10%" class="text-center"><%= cart.precio %></td>
              <td width="10%" class="text-end"><%= importe %></td>  
            </tr>
          <% end %>
          <tr>
            <td colspan="5" class="text-end fw-bold fs-5">TOTAL A PAGAR</td>
            <td class="text-end fw-bold fs-5"><%= total %></td>
          </tr>
        <tbody>  
      </table>  
      <br>
      <%= link_to "Confirmar y Pagar", confirma_pedido_path(current_user.id), class: "btn btn-primary" %> 
      <%= link_to "Cancelar", vaciar_carrito_path(current_user.id), class: "btn btn-danger" %>  
    </div>
  </div>  
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>