config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :order_details
  resources :orders
  resources :customers
  resources :carts
  resources :categories
  resources :banners
  resources :products
  get 'home/index'
  get 'home/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html  
  get "/users/sign_out", to: "users#sign_out"
  # Defines the root path route ("/")
  root "home#index"
  get "/productos/buscador", to: "products#buscador", as: "buscar_producto"
  get "/productos/:id/agregar_carrito", to: "products#agregar_carrito", as: "agregar_carrito"
  get "/carrito/:id/vaciar_carrito", to: "carts#vaciar_carrito", as: "vaciar_carrito"
  get "/productos/:id/disminuye_cantidad", to: "products#disminuye_cantidad", as: "disminuye_cantidad"
  get "/productos/:id/aumenta_cantidad", to: "products#aumenta_cantidad", as: "aumenta_cantidad"
  get "/customer/:id/valida_cliente", to: "customers#valida_cliente", as: "valida_cliente"
  get "/order/:id/pedido", to: "orders#genera_pedido", as: "genera_orden"
  get "/order/:id/confirma", to: "orders#confirma_pedido", as: "confirma_pedido"

  namespace :paypal do
    resources :checkouts, only: [:create] do
      collection do
        get :complete
      end
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.where(user_id: current_user.id, pedido: 0)
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def vaciar_carrito
    carrito = Cart.where(user_id: params[:id], pedido: 0)
    
    carrito.delete_all
    
    if carrito
      redirect_to carts_url
    end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.require(:cart).permit(:fecha, :cantidad, :precio, :pedido, :user_id, :product_id)
    end
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
  <p>
    <strong>Fecha:</strong>
    <%= cart.fecha %>
  </p>

  <p>
    <strong>Cantidad:</strong>
    <%= cart.cantidad %>
  </p>

  <p>
    <strong>Precio:</strong>
    <%= cart.precio %>
  </p>

  <p>
    <strong>Pedido:</strong>
    <%= cart.pedido %>
  </p>

  <p>
    <strong>User:</strong>
    <%= cart.user_id %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= cart.product_id %>
  </p>

</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :fecha, style: "display: block" %>
    <%= form.date_field :fecha %>
  </div>

  <div>
    <%= form.label :cantidad, style: "display: block" %>
    <%= form.number_field :cantidad %>
  </div>

  <div>
    <%= form.label :precio, style: "display: block" %>
    <%= form.text_field :precio %>
  </div>

  <div>
    <%= form.label :pedido, style: "display: block" %>
    <%= form.check_box :pedido %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<br><br>
<div class="container">

  <div class="card">
    <div class="card-header">
      <h1>Mi Carrito</h1>
    </div>
    <div class="card-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>&nbsp;</th>
            <th>Codigo</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Cantidad</th>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
          <% @carts.each do |cart| %>
            <tr>
            
              <td><%= image_tag(cart.product.image, style: "max-width: 20%") if cart.product.image.attached? %></td>
              <td><%= cart.product.codigo %></td>
              <td><%= cart.product.nombre %></td>
              <td><%= cart.precio %></td>              
              <td><%= link_to '<strong>-</strong>'.html_safe, disminuye_cantidad_path(cart.id) %>
                  <%= cart.cantidad %><%= link_to '<strong>+</strong>'.html_safe, aumenta_cantidad_path(cart.id) %>
              </td>
              <td><%#= link_to "Modificar", edit_product_path(product), class: "btn btn-secondary" %></td>
              <td><%= button_to "Eliminar", cart, method: :delete, class: "btn btn-danger" %>
              
            </tr>
          <% end %>
        <tbody>  
      </table>  
      <br>
      <%= link_to "Pagar", valida_cliente_path(current_user.id), class: "btn btn-primary" %> 
      <%= link_to "Ver mas Productos", buscar_producto_path, class: "btn btn-secondary" %>  
      <%= link_to "Vaciar Carrito", vaciar_carrito_path(current_user.id), class: "btn btn-danger" %>
    </div>
  </div>  
</div>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cart %>

<div>
  <%= link_to "Edit this cart", edit_cart_path(@cart) %> |
  <%= link_to "Back to carts", carts_path %>

  <%= button_to "Destroy this cart", @cart, method: :delete %>
</div>