config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :order_details
  resources :orders
  resources :customers
  resources :carts
  resources :categories
  resources :banners
  resources :products
  get 'home/index'
  get 'home/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html  
  get "/users/sign_out", to: "users#sign_out"
  # Defines the root path route ("/")
  root "home#index"
  get "/productos/buscador", to: "products#buscador", as: "buscar_producto"
  get "/productos/:id/agregar_carrito", to: "products#agregar_carrito", as: "agregar_carrito"
  get "/carrito/:id/vaciar_carrito", to: "carts#vaciar_carrito", as: "vaciar_carrito"
  get "/productos/:id/disminuye_cantidad", to: "products#disminuye_cantidad", as: "disminuye_cantidad"
  get "/productos/:id/aumenta_cantidad", to: "products#aumenta_cantidad", as: "aumenta_cantidad"
  get "/customer/:id/valida_cliente", to: "customers#valida_cliente", as: "valida_cliente"
  get "/order/:id/pedido", to: "orders#genera_pedido", as: "genera_orden"
  get "/order/:id/confirma", to: "orders#confirma_pedido", as: "confirma_pedido"

  namespace :paypal do
    resources :checkouts, only: [:create] do
      collection do
        get :complete
      end
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_one_attached :image
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def buscador
    @products = Product.order(:nombre)
  end

  def agregar_carrito

    cart = Cart.find_by(product_id: params[:id], user_id: current_user.id, pedido: 0)
    if cart
      cart.cantidad += 1
      cart.save
    else
      carrito = Cart.new()
      producto = Product.find(params[:id])
      carrito.product_id = producto.id
      carrito.cantidad = 1
      carrito.user_id = current_user.id
      carrito.precio = producto.precio
      carrito.pedido = 0
      carrito.save
    end  

    redirect_to buscar_producto_path
  end

  def disminuye_cantidad
    carrito = Cart.find(params[:id])

    if carrito.cantidad == 1
      carrito.delete
    else  
      carrito.cantidad -= 1
      carrito.save
    end  

    redirect_to carts_url 
  end

  def aumenta_cantidad
    carrito = Cart.find(params[:id])
    carrito.cantidad += 1
    carrito.save
    
    redirect_to carts_url 
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
     # faltan datos del modelo.
    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:codigo, :nombre, :descripcion, :precio, :existencia, :category_id, :image)
    end
end

app/views/products/_form.html.erb
  <%= form_with(model: product) do |form| %>
    <% if product.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
          <% product.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :nombre, style: "display: block" %>
      <%= form.text_field :nombre, class: 'form-control' %>      
    </div>
  
    <div class="field">
      <%= form.label :codigo, style: "display: block" %>
      <%= form.text_field :codigo, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :precio, style: "display: block" %>
      <%= form.number_field :precio, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :existencia, style: "display: block" %>
      <%= form.number_field :existencia, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :descripcion, style: "display: block" %>
      <%= form.text_area :descripcion, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :Categoria, style: "display: block" %>
      <%= form.collection_select :category_id, Category.order(:nombre), :id, :nombre %>
    </div>  

    <div class="field">
      <%= form.label :image, style: "display: block" %>
      <%= form.file_field :image,  class: 'form-control' %>      
    </div>

    </br>
    <div>
      <%= form.hidden_field :category_id, value: 1 %>
      <%= form.submit "Agregar", class: 'btn btn-primary' %>
      
    </div>
  <% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">

  <div class="card" style="width: 18rem;">
    <% if product.image.attached? %>
   
      <img class="card-img-top" src='<%= (url_for(product.image)) %>'>

    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= product.nombre %></h5>
      <p class="card-text">
        <span style="color: red">$<%= product.precio %></span>      
          
        </div> 
      </p>      
    </div>
  </div>

</div>

app/views/products/buscador.html.erb
<br><br>
<div class="container">
    <div class="card">
        <div class="card-header">
            <h1>Buscar Productos</h1>
        </div>
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                    <th>Imagen</th>
                    <th>Codigo</th>
                    <th>Nombre</th>
                    <th>Descripcion</th>
                    <th>Precio</th>
                    <th>Existencia</th>
                    <th>Categoria</th>
                    <th colspan="2"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @products.each do |product| %>
                    <tr>
                        <td><%= image_tag(product.image, style: "max-width: 20%") if product.image.attached? %></td>
                        <td><%= product.codigo %></td>
                        <td><%= product.nombre %></td>
                        <td><%= product.descripcion %></td>
                        <td><%= product.precio %></td>
                        <td><%= product.existencia %></td>
                        <td><%= product.category.nombre %></td>
                        <td><%= link_to "Agregar al carrito", agregar_carrito_path(product), class: "btn btn-primary" %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>    
    </div>
</div>

app/views/products/edit.html.erb
  <h1>Editing product</h1>

  <%= render "form", product: @product %>

  <br>

  <div>
    <%= link_to "Show this product", @product %> |
    <%= link_to "Back to products", products_path %>
  </div>

app/views/products/index.html.erb
<br><br>
<div class="container">

  <div class="card">
    <div class="card-header">
      <h1>Listado de Productos</h1>
    </div>
    <div class="card-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Imagen</th>
            <th>Codigo</th>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Precio</th>
            <th>Existencia</th>
            <th>Categoria</th>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td><%= image_tag(product.image, style: "max-width: 20%") if product.image.attached? %></td>
              <td><%= product.codigo %></td>
              <td><%= product.nombre %></td>
              <td><%= product.descripcion %></td>
              <td><%= product.precio %></td>
              <td><%= product.existencia %></td>
              <td><%= product.category.nombre %></td>
              <td><%= link_to "Modificar", edit_product_path(product), class: "btn btn-secondary" %></td>
              <td><%= button_to "Eliminar", product, method: :delete, class: "btn btn-danger" %>
              
            </tr>
          <% end %>
        </tbody>  
      </table>  
      <br>
      <%= link_to "Nuevo", new_product_path, class: "btn btn-primary" %>  
    </div>
  </div>  
</div>

app/views/products/new.html.erb
<div class="container" style="width:65%">
  <h1>Nuevo Producto</h1>

  <%= render "form", product: @product %>

  <br>

  <div>
    <%= link_to "Volver a los productos", products_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>